### ISSUE TITLE
Translations!

### ISSUE THREAD

**Issue by waelk10** [waelk10/Metronome#4]
Anyone that'll be willing to help with the translations? just provide me with a file that has the original and translated text, i'll do the rest.

**Comment by licaon-kter** [comment]
Do make an account so translators can work directly with the file (eg. [strings.xml](https://github.com/waelk10/Metronome/blob/master/app/src/main/res/values/strings.xml) )

* https://www.transifex.com/ (free for open source)
* https://crowdin.com/ (free for open source)
* https://hosted.weblate.org/ (free)

I listed them in my order of preference since I worked with all of them.

**Comment by waelk10** [comment]
Not a priority!

**Comment by waelk10** [comment]
Accidentally reopened the issue, so I'm closing it again. 
Just to clarify, if anyone has a translation they'd like to submit, feel free to do so, if the XML files a pre-formatted that'd be even better too. 
I'll gladly merge any translation.
